services:
  wordpress:
    image: wordpress:6.8.3
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1
      - WORDPRESS_DEBUG_LOG=1
      - WORDPRESS_DEBUG_DISPLAY=1
      - UPLOAD_MAX_FILESIZE=64M
      - POST_MAX_SIZE=64M
      - MAX_EXECUTION_TIME=300
      - MEMORY_LIMIT=256M
    volumes:
      - wordpress_data:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/wp-associates
      - ./vendor:/var/www/html/wp-content/plugins/wp-associates/vendor
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
